const TOURS = {
  'wild-atlantic': {
    id: 'wild-atlantic',
    name: 'Wild Atlantic Way',
    eyebrow: 'Coastal Adventure',
    price: 89,
    priceLabel: 'per person',
    duration: '8 Hours',
    groupSize: 'Up to 12',
    type: 'Full Day',
    difficulty: 'Easy',
    image: 'images/tour-wild-atlantic.jpg',
    badge: 'Most Popular',
    desc: "Journey along Ireland's most dramatic coastline — soaring sea cliffs, windswept headlands, and charming harbour villages stretching from Donegal to Sligo.",
    descExtra: "This tour takes you along one of the world's great coastal drives, stopping at the most spectacular viewpoints and hidden gems that only a local guide would know. You'll witness the raw power of the Atlantic, walk ancient cliff paths, and end the day with a pint in a traditional Irish harbour pub.",
    highlights: [
      'Slieve League Cliffs — 3× higher than the Cliffs of Moher',
      'Malin Head — Ireland\'s most northerly point',
      'Mullaghmore Head with stunning ocean views',
      'Bundoran surf beach stop',
      'Traditional Irish pub lunch in a harbour village',
    ],
    itinerary: [
      { time: '8:00am', title: 'Departure', desc: 'Pick-up from Derry / Sligo town centre. Coffee and pastries on board.' },
      { time: '9:30am', title: 'Malin Head', desc: "Ireland's northernmost point — dramatic cliffs and sweeping Atlantic views." },
      { time: '11:00am', title: 'Slieve League Cliffs', desc: 'Walk the cliff paths with your guide. One of Ireland\'s most spectacular natural sights.' },
      { time: '1:00pm', title: 'Lunch', desc: 'Traditional Irish lunch in a local harbour pub — included in your price.' },
      { time: '2:30pm', title: 'Coastal Villages', desc: 'Stop at charming fishing villages along the Wild Atlantic Way.' },
      { time: '4:30pm', title: 'Bundoran', desc: 'Ireland\'s surf capital — optional beach walk before heading back.' },
      { time: '6:00pm', title: 'Return', desc: 'Drop-off at original pick-up point.' },
    ],
    included: ['Expert local guide', 'Luxury coach transport', 'Pub lunch', 'Entry to all sites', 'Free pick-up'],
    excluded: ['Personal travel insurance', 'Gratuities', 'Additional food & drinks'],
    gallery: ['images/tour-wild-atlantic.jpg', 'images/tour-donegal-highlands.jpg', 'images/tour-sligo-yeats.jpg'],
  },

  'giants-causeway': {
    id: 'giants-causeway',
    name: "Giant's Causeway & Antrim Coast",
    eyebrow: 'UNESCO World Heritage',
    price: 105,
    priceLabel: 'per person',
    duration: 'Full Day',
    groupSize: 'Up to 10',
    type: 'Premium',
    difficulty: 'Easy–Moderate',
    image: 'images/tour-giants-causeway.jpg',
    badge: null,
    desc: "Explore the UNESCO World Heritage Site of Giant's Causeway, cross the legendary Carrick-a-Rede rope bridge, and drive the stunning Antrim Coastal Road.",
    descExtra: "This is our most iconic tour, following the dramatic Antrim Coast past ruined castles, through the famous Dark Hedges avenue, and onto the extraordinary basalt columns of Giant's Causeway — formed 60 million years ago by volcanic activity.",
    highlights: [
      "Giant's Causeway — 40,000 interlocking basalt columns",
      'Carrick-a-Rede rope bridge crossing (60m above the sea)',
      'Dunluce Castle — perched dramatically on the cliff edge',
      "The Dark Hedges — Game of Thrones' King's Road",
      'Ballintoy Harbour and White Park Bay',
    ],
    itinerary: [
      { time: '7:30am', title: 'Departure', desc: 'Pick-up from Derry city centre.' },
      { time: '9:00am', title: 'Dark Hedges', desc: "The iconic beech tree avenue made famous by Game of Thrones." },
      { time: '10:00am', title: "Giant's Causeway", desc: 'Two hours to explore the UNESCO site with your guide explaining its volcanic origins.' },
      { time: '12:30pm', title: 'Lunch', desc: 'Lunch at a local restaurant in Bushmills village.' },
      { time: '2:00pm', title: 'Carrick-a-Rede', desc: 'Cross the famous rope bridge — 60 metres above the crashing Atlantic.' },
      { time: '3:30pm', title: 'Dunluce Castle', desc: "Explore the dramatic ruins of this medieval clifftop castle." },
      { time: '5:30pm', title: 'Return', desc: 'Scenic coastal drive back to Derry.' },
    ],
    included: ['Expert local guide', 'Luxury coach transport', 'Giant\'s Causeway entry', 'Carrick-a-Rede entry', 'Free pick-up'],
    excluded: ['Lunch (budget ~€15)', 'Personal travel insurance', 'Gratuities'],
    gallery: ['images/tour-giants-causeway.jpg', 'images/tour-wild-atlantic.jpg', 'images/tour-fermanagh.jpg'],
  },

  'donegal-highlands': {
    id: 'donegal-highlands',
    name: 'Donegal Highlands Explorer',
    eyebrow: 'Mountain & Wilderness',
    price: 72,
    priceLabel: 'per person',
    duration: '6 Hours',
    groupSize: 'Up to 14',
    type: 'Half Day+',
    difficulty: 'Easy',
    image: 'images/tour-donegal-highlands.jpg',
    badge: null,
    desc: "Venture into the rugged heart of Donegal — ancient peat bogs, glassy mountain lakes, and the haunting beauty of Glenveagh National Park.",
    descExtra: "Donegal's highlands are one of Ireland's best-kept secrets — vast, wild, and breathtakingly beautiful. Your guide will lead you through glacially carved valleys, past crystal-clear mountain lakes, and into Glenveagh, Ireland's second-largest national park.",
    highlights: [
      'Glenveagh National Park & Castle',
      "Mount Errigal — Donegal's iconic quartzite peak",
      'Dunlewy Lough — a hauntingly beautiful glacial lake',
      'Traditional peat bog walk with a local farmer',
      'Afternoon tea at a working sheep farm',
    ],
    itinerary: [
      { time: '9:00am', title: 'Departure', desc: 'Pick-up from Letterkenny or Donegal Town.' },
      { time: '10:00am', title: 'Mount Errigal', desc: 'Stop at the base of Donegal\'s most iconic mountain for photos and a short walk.' },
      { time: '11:00am', title: 'Glenveagh', desc: 'Explore the national park and castle gardens with your guide.' },
      { time: '1:00pm', title: 'Sheep Farm', desc: 'Visit a local working farm for a demonstration and traditional afternoon tea.' },
      { time: '2:30pm', title: 'Dunlewy', desc: 'Walk the shore of the ghostly Dunlewy Lough and visit the ruined church.' },
      { time: '3:30pm', title: 'Return', desc: 'Scenic drive back through the highlands.' },
    ],
    included: ['Expert local guide', 'Luxury coach transport', 'Afternoon tea at farm', 'Park entry fees', 'Free pick-up'],
    excluded: ['Lunch', 'Personal travel insurance', 'Gratuities'],
    gallery: ['images/tour-donegal-highlands.jpg', 'images/tour-wild-atlantic.jpg', 'images/why-choose-us.jpg'],
  },

  'sligo-yeats': {
    id: 'sligo-yeats',
    name: 'Sligo & Yeats Country',
    eyebrow: 'Literature & Landscape',
    price: 65,
    priceLabel: 'per person',
    duration: '5 Hours',
    groupSize: 'Up to 16',
    type: 'Cultural',
    difficulty: 'Easy',
    image: 'images/tour-sligo-yeats.jpg',
    badge: null,
    desc: "Walk in the footsteps of W.B. Yeats through the landscape that inspired his greatest poetry — Benbulben, Lough Gill, and the mysterious Isle of Innisfree.",
    descExtra: "County Sligo was the childhood home of Nobel Prize-winning poet W.B. Yeats, and its landscapes run through almost every poem he wrote. This tour brings his words to life, visiting the places he loved and is buried, with readings from his work along the way.",
    highlights: [
      'Benbulben — the iconic flat-topped mountain Yeats called home',
      "Yeats's grave at Drumcliffe Church",
      'Lough Gill boat trip to the Isle of Innisfree',
      'Sligo town — galleries and the Yeats Building',
      'Carrowmore Megalithic Cemetery',
    ],
    itinerary: [
      { time: '10:00am', title: 'Departure', desc: 'Pick-up from Sligo town centre.' },
      { time: '10:30am', title: 'Drumcliffe', desc: "Visit Yeats's grave beneath Benbulben — hear his epitaph read aloud." },
      { time: '11:30am', title: 'Benbulben', desc: 'Panoramic stops around the mountain with poetry readings in situ.' },
      { time: '1:00pm', title: 'Lough Gill', desc: "Boat trip across the lake to the Isle of Innisfree — Yeats's most famous poem." },
      { time: '2:30pm', title: 'Carrowmore', desc: 'Walk through one of Europe\'s oldest megalithic cemeteries.' },
      { time: '3:30pm', title: 'Return', desc: 'Back to Sligo town centre.' },
    ],
    included: ['Expert local guide', 'Luxury coach transport', 'Innisfree boat trip', 'Cemetery entry', 'Free pick-up'],
    excluded: ['Lunch', 'Personal travel insurance', 'Gratuities'],
    gallery: ['images/tour-sligo-yeats.jpg', 'images/tour-wild-atlantic.jpg', 'images/tour-donegal-highlands.jpg'],
  },

  'fermanagh': {
    id: 'fermanagh',
    name: 'Fermanagh Lakelands',
    eyebrow: 'Lakes & Legends',
    price: 78,
    priceLabel: 'per person',
    duration: '7 Hours',
    groupSize: 'Up to 12',
    type: 'Nature',
    difficulty: 'Easy',
    image: 'images/tour-fermanagh.jpg',
    badge: null,
    desc: "Discover the tranquil lake district of County Fermanagh — ancient island monasteries, stunning cave systems, and the legendary Shannon–Erne waterway.",
    descExtra: "Fermanagh's lakelands are a world apart — a serene landscape of interconnected loughs, wooded islands, and ancient monuments. From the UNESCO-listed Marble Arch Caves to the 1,400-year-old monastery on Devenish Island, this tour is rich with history and natural beauty.",
    highlights: [
      'Devenish Island — 6th century monastic site by boat',
      'Marble Arch Caves UNESCO Geopark',
      'Enniskillen Castle & Museum',
      'Florence Court estate gardens',
      'Lough Erne sunset cruise',
    ],
    itinerary: [
      { time: '8:30am', title: 'Departure', desc: 'Pick-up from Enniskillen town centre.' },
      { time: '9:30am', title: 'Devenish Island', desc: 'Boat trip to the 6th century monastic island — explore the round tower and ruins.' },
      { time: '11:00am', title: 'Marble Arch Caves', desc: "Guided tour of one of Europe's finest show caves — underground rivers and formations." },
      { time: '1:00pm', title: 'Lunch', desc: 'Lunch at Florence Court estate.' },
      { time: '2:30pm', title: 'Enniskillen Castle', desc: 'Explore the castle and Fermanagh County Museum.' },
      { time: '4:00pm', title: 'Lough Erne', desc: 'Sunset cruise on the lough (weather permitting).' },
      { time: '5:30pm', title: 'Return', desc: 'Back to Enniskillen.' },
    ],
    included: ['Expert local guide', 'Luxury coach transport', 'Devenish boat trip', 'Cave entry', 'Castle entry', 'Free pick-up'],
    excluded: ['Lunch (budget ~€15)', 'Personal travel insurance', 'Gratuities'],
    gallery: ['images/tour-fermanagh.jpg', 'images/tour-giants-causeway.jpg', 'images/tour-sligo-yeats.jpg'],
  },

  'private': {
    id: 'private',
    name: 'Private Bespoke Tour',
    eyebrow: 'Fully Tailored Experience',
    price: 220,
    priceLabel: 'per group',
    duration: 'Flexible',
    groupSize: 'Any size',
    type: 'Bespoke',
    difficulty: 'Your choice',
    image: 'images/tour-private.jpg',
    badge: null,
    desc: "Design your perfect Irish adventure. Our expert guides will build a fully custom itinerary around your interests, pace, group size, and schedule.",
    descExtra: "Whether you're celebrating a special occasion, travelling with family, or simply want the freedom to explore at your own pace — our private tours are built entirely around you. Choose any combination of destinations across the north-west, and we'll handle everything.",
    highlights: [
      'Fully customisable route, stops, and duration',
      'Dedicated private guide just for your group',
      'Any combination of north-west destinations',
      'Perfect for celebrations, family groups, or corporate trips',
      'Multi-day itineraries available',
    ],
    itinerary: [
      { time: 'Flexible', title: 'Your Schedule', desc: 'We work around your preferred start time and pace.' },
      { time: 'Flexible', title: 'Your Destinations', desc: 'Pick any combination of our tours, or tell us what interests you most.' },
      { time: 'Flexible', title: 'Your Meals', desc: 'We can arrange restaurant reservations, packed lunches, or cookery experiences.' },
      { time: 'Flexible', title: 'Your Accommodation', desc: 'Multi-day tours can include accommodation arrangements on request.' },
      { time: 'Flexible', title: 'Your Return', desc: 'Drop-off wherever suits you — hotel, airport, or home.' },
    ],
    included: ['Dedicated private guide', 'Luxury private vehicle', 'Custom itinerary planning', 'All entry fees', 'Flexible pick-up/drop-off'],
    excluded: ['Meals (unless arranged)', 'Accommodation', 'Personal travel insurance'],
    gallery: ['images/tour-private.jpg', 'images/tour-wild-atlantic.jpg', 'images/tour-giants-causeway.jpg'],
  },
};
